import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { formatDateHeader } from "./dateUtils";

function escapeHtml(str) {
  return String(str ?? "").replace(/[&<>"']/g, (c) => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
  }[c]));
}

function field(label, value) {
  return `
    <div class="section">
      <div class="label">${escapeHtml(label)}</div>
      <div class="value">${escapeHtml(value || "—")}</div>
    </div>`;
}

function medsTable(medications) {
  if (!medications || medications.length === 0) {
    return `<div class="section"><div class="label">Medications</div><div class="value">None recorded</div></div>`;
  }
  const rows = medications.map((m) => `
    <tr>
      <td>${escapeHtml(m.drug_name)}</td>
      <td>${escapeHtml(m.frequency || "—")}</td>
      <td>${escapeHtml(m.duration || "—")}</td>
    </tr>`).join("");
  return `
    <div class="section">
      <div class="label">Medications</div>
      <table class="meds">
        <tr><th>Drug</th><th>Frequency</th><th>Duration</th></tr>
        ${rows}
      </table>
    </div>`;
}

export async function exportStayToPdf(detail, medications) {
  const html = `
    <html>
    <head>
      <meta charset="utf-8" />
      <style>
        body { font-family: -apple-system, Helvetica, Arial, sans-serif; padding: 32px; color: #16202c; }
        h1 { font-size: 22px; margin: 0 0 4px 0; }
        .meta { color: #5a6b7d; font-size: 13px; margin-bottom: 24px; }
        .section { margin-bottom: 18px; }
        .label { font-size: 11px; text-transform: uppercase; letter-spacing: 0.6px; color: #1d5fbf; font-weight: 700; margin-bottom: 4px; }
        .value { font-size: 14px; line-height: 1.55; white-space: pre-wrap; }
        hr { border: none; border-top: 1px solid #dfe4ea; margin: 20px 0; }
        table.meds { width: 100%; border-collapse: collapse; margin-top: 6px; }
        table.meds th, table.meds td { border: 1px solid #dfe4ea; padding: 6px 10px; font-size: 13px; text-align: left; }
        table.meds th { background: #f0f4fa; color: #1d5fbf; }
        .footer { margin-top: 32px; font-size: 10px; color: #9aa5b1; }
      </style>
    </head>
    <body>
      <h1>${escapeHtml(detail.first_name)} ${escapeHtml(detail.last_name)}</h1>
      <div class="meta">
        MRN ${escapeHtml(detail.mrn)}${detail.rch_id ? ` &middot; RCH ${escapeHtml(detail.rch_id)}` : ""}
        ${detail.phone_number ? ` &middot; ${escapeHtml(detail.phone_number)}` : ""}
      </div>
      <hr />
      ${field("Address", detail.address)}
      ${field("VHN Name", detail.vhn_name)}
      ${field("VHN Number", detail.vhn_number)}
      ${field("Date of Admission", formatDateHeader(detail.admission_date))}
      ${field("Date of Discharge", formatDateHeader(detail.discharge_date))}
      ${field("Primary Diagnosis", detail.primary_diagnosis)}
      ${field("Hospital Course", detail.hospital_course)}
      ${field("Discharge Condition", detail.discharge_condition)}
      ${medsTable(medications)}
      <div class="footer">Generated by Hospital Records</div>
    </body>
    </html>`;

  const { uri } = await Print.printToFileAsync({ html, base64: false });

  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, {
      mimeType: "application/pdf",
      dialogTitle: "Export Record",
      UTI: "com.adobe.pdf",
    });
  }
  return uri;
}
