import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { isoToDisplay } from "./dateUtils";

function escapeHtml(str) {
  return String(str ?? "").replace(/[&<>"']/g, (c) => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
  }[c]));
}

function field(label, value) {
  return `
    <div class="section">
      <div class="label">${escapeHtml(label)}</div>
      <div class="value">${escapeHtml(value || "—")}</div>
    </div>`;
}

export async function exportStayToPdf(detail) {
  const html = `
    <html>
    <head>
      <meta charset="utf-8" />
      <style>
        body { font-family: -apple-system, Helvetica, Arial, sans-serif; padding: 32px; color: #16202c; }
        h1 { font-size: 22px; margin: 0 0 4px 0; }
        .meta { color: #5a6b7d; font-size: 13px; margin-bottom: 24px; }
        .section { margin-bottom: 18px; }
        .label { font-size: 11px; text-transform: uppercase; letter-spacing: 0.6px; color: #1d5fbf; font-weight: 700; margin-bottom: 4px; }
        .value { font-size: 14px; line-height: 1.55; white-space: pre-wrap; }
        hr { border: none; border-top: 1px solid #dfe4ea; margin: 20px 0; }
        .footer { margin-top: 32px; font-size: 10px; color: #9aa5b1; }
      </style>
    </head>
    <body>
      <h1>${escapeHtml(detail.first_name)} ${escapeHtml(detail.last_name)}</h1>
      <div class="meta">MRN ${escapeHtml(detail.mrn)} &middot; DOB ${isoToDisplay(detail.dob)}</div>
      <hr />
      ${field("Admission", detail.admission_date)}
      ${field("Discharge", detail.discharge_date)}
      ${field("Primary Diagnosis", detail.primary_diagnosis)}
      ${field("Daily Progress Notes", detail.daily_progress_notes)}
      ${field("Hospital Course", detail.hospital_course)}
      ${field("Treatment Given", detail.treatment_given)}
      ${field("Discharge Condition", detail.discharge_condition)}
      ${field("Discharge Advice", detail.discharge_advice)}
      <div class="footer">Generated by Hospital Records</div>
    </body>
    </html>`;

  const { uri } = await Print.printToFileAsync({ html, base64: false });

  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, {
      mimeType: "application/pdf",
      dialogTitle: "Export Record",
      UTI: "com.adobe.pdf",
    });
  }
  return uri;
}
